C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.4.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapelectron_ppm_prefix_eval_nonuniform (elec
     &tron_ppm_prefix_eval_nonuniformf2pywrap, Num_gam_e, x_edge, q, q_l
     &eft, q_right, prefix, x_eval)
      external electron_ppm_prefix_eval_nonuniform
      integer Num_gam_e
      real(kind=8) x_eval
      real(kind=8) x_edge(1 + Num_gam_e)
      real(kind=8) q(Num_gam_e)
      real(kind=8) q_left(Num_gam_e)
      real(kind=8) q_right(Num_gam_e)
      real(kind=8) prefix(1 + Num_gam_e)
      real(kind=8) electron_ppm_prefix_eval_nonuniformf2pywrap
      real(kind=8)  electron_ppm_prefix_eval_nonuniform
      electron_ppm_prefix_eval_nonuniformf2pywrap = electron_ppm_p
     &refix_eval_nonuniform(Num_gam_e, x_edge, q, q_left, q_right, prefi
     &x, x_eval)
      end


      subroutine f2pywrapelectron_loglinear_cell_int (electron_log
     &linear_cell_intf2pywrap, qlog_center, slope, x_center, xa, xb)
      external electron_loglinear_cell_int
      real(kind=8) qlog_center
      real(kind=8) slope
      real(kind=8) x_center
      real(kind=8) xa
      real(kind=8) xb
      real(kind=8) electron_loglinear_cell_intf2pywrap
      real(kind=8)  electron_loglinear_cell_int
      electron_loglinear_cell_intf2pywrap = electron_loglinear_cel
     &l_int(qlog_center, slope, x_center, xa, xb)
      end


      subroutine f2pywrapelectron_log_prefix_eval_nonuniform (elec
     &tron_log_prefix_eval_nonuniformf2pywrap, Num_gam_e, x_edge, prefix
     &, qlog, slope, x_center, x_eval)
      external electron_log_prefix_eval_nonuniform
      integer Num_gam_e
      real(kind=8) x_eval
      real(kind=8) x_edge(1 + Num_gam_e)
      real(kind=8) prefix(1 + Num_gam_e)
      real(kind=8) qlog(Num_gam_e)
      real(kind=8) slope(Num_gam_e)
      real(kind=8) x_center(Num_gam_e)
      real(kind=8) electron_log_prefix_eval_nonuniformf2pywrap
      real(kind=8)  electron_log_prefix_eval_nonuniform
      electron_log_prefix_eval_nonuniformf2pywrap = electron_log_p
     &refix_eval_nonuniform(Num_gam_e, x_edge, prefix, qlog, slope, x_ce
     &nter, x_eval)
      end


      subroutine f2pywrapelectron_dnx_powerlaw_integral (electron_
     &dnx_powerlaw_integralf2pywrap, A, slope, x_lo, x_hi)
      external electron_dnx_powerlaw_integral
      real(kind=8) A
      real(kind=8) slope
      real(kind=8) x_lo
      real(kind=8) x_hi
      real(kind=8) electron_dnx_powerlaw_integralf2pywrap
      real(kind=8)  electron_dnx_powerlaw_integral
      electron_dnx_powerlaw_integralf2pywrap = electron_dnx_powerl
     &aw_integral(A, slope, x_lo, x_hi)
      end


      subroutine f2pywrapelectron_dnx_powerlaw_cutoff_value (elect
     &ron_dnx_powerlaw_cutoff_valuef2pywrap, x, coeff, slope, Gam_e_max)
      external electron_dnx_powerlaw_cutoff_value
      real(kind=8) x
      real(kind=8) coeff
      real(kind=8) slope
      real(kind=8) Gam_e_max
      real(kind=8) electron_dnx_powerlaw_cutoff_valuef2pywrap
      real(kind=8)  electron_dnx_powerlaw_cutoff_value
      electron_dnx_powerlaw_cutoff_valuef2pywrap = electron_dnx_po
     &werlaw_cutoff_value(x, coeff, slope, Gam_e_max)
      end


      subroutine f2pywrapelectron_dnx_gauss3_integral (electron_dn
     &x_gauss3_integralf2pywrap, coeff, slope, Gam_e_max, x_lo, x_hi)
      external electron_dnx_gauss3_integral
      real(kind=8) coeff
      real(kind=8) slope
      real(kind=8) Gam_e_max
      real(kind=8) x_lo
      real(kind=8) x_hi
      real(kind=8) electron_dnx_gauss3_integralf2pywrap
      real(kind=8)  electron_dnx_gauss3_integral
      electron_dnx_gauss3_integralf2pywrap = electron_dnx_gauss3_i
     &ntegral(coeff, slope, Gam_e_max, x_lo, x_hi)
      end


      subroutine f2pywrapelectron_minmod (electron_minmodf2pywrap,
     & a, b)
      external electron_minmod
      real(kind=8) a
      real(kind=8) b
      real(kind=8) electron_minmodf2pywrap
      real(kind=8)  electron_minmod
      electron_minmodf2pywrap = electron_minmod(a, b)
      end


      subroutine f2pywrapelectron_minmod3 (electron_minmod3f2pywra
     &p, a, b, c)
      external electron_minmod3
      real(kind=8) a
      real(kind=8) b
      real(kind=8) c
      real(kind=8) electron_minmod3f2pywrap
      real(kind=8)  electron_minmod3
      electron_minmod3f2pywrap = electron_minmod3(a, b, c)
      end


      subroutine f2pywrapelectron_cell_linear_integral (electron_c
     &ell_linear_integralf2pywrap, qc, slope, xc, xl, xr)
      external electron_cell_linear_integral
      real(kind=8) qc
      real(kind=8) slope
      real(kind=8) xc
      real(kind=8) xl
      real(kind=8) xr
      real(kind=8) electron_cell_linear_integralf2pywrap
      real(kind=8)  electron_cell_linear_integral
      electron_cell_linear_integralf2pywrap = electron_cell_linear
     &_integral(qc, slope, xc, xl, xr)
      end


      subroutine f2pywrapelectron_ppm_cell_int (electron_ppm_cell_
     &intf2pywrap, qc, q_left, q_right, cell_lo, d_x, xl, xr)
      external electron_ppm_cell_int
      real(kind=8) qc
      real(kind=8) q_left
      real(kind=8) q_right
      real(kind=8) cell_lo
      real(kind=8) d_x
      real(kind=8) xl
      real(kind=8) xr
      real(kind=8) electron_ppm_cell_intf2pywrap
      real(kind=8)  electron_ppm_cell_int
      electron_ppm_cell_intf2pywrap = electron_ppm_cell_int(qc, q_
     &left, q_right, cell_lo, d_x, xl, xr)
      end


      subroutine f2pywrapelectron_prefix_integral_eval (electron_p
     &refix_integral_evalf2pywrap, Num_gam_e, d_x, q, slope, prefix, x_e
     &val)
      external electron_prefix_integral_eval
      integer Num_gam_e
      real(kind=8) d_x
      real(kind=8) x_eval
      real(kind=8) q(Num_gam_e)
      real(kind=8) slope(Num_gam_e)
      real(kind=8) prefix(1 + Num_gam_e)
      real(kind=8) electron_prefix_integral_evalf2pywrap
      real(kind=8)  electron_prefix_integral_eval
      electron_prefix_integral_evalf2pywrap = electron_prefix_inte
     &gral_eval(Num_gam_e, d_x, q, slope, prefix, x_eval)
      end


      subroutine f2pywrapelectron_ppm_prefix_eval (electron_ppm_pr
     &efix_evalf2pywrap, Num_gam_e, d_x, q, q_left, q_right, prefix, x_e
     &val)
      external electron_ppm_prefix_eval
      integer Num_gam_e
      real(kind=8) d_x
      real(kind=8) x_eval
      real(kind=8) q(Num_gam_e)
      real(kind=8) q_left(Num_gam_e)
      real(kind=8) q_right(Num_gam_e)
      real(kind=8) prefix(1 + Num_gam_e)
      real(kind=8) electron_ppm_prefix_evalf2pywrap
      real(kind=8)  electron_ppm_prefix_eval
      electron_ppm_prefix_evalf2pywrap = electron_ppm_prefix_eval(
     &Num_gam_e, d_x, q, q_left, q_right, prefix, x_eval)
      end

