!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.4.4)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitConstants(f2pysetupfunc)
      use Constants, only : zero
      use Constants, only : one
      use Constants, only : two
      use Constants, only : ten
      use Constants, only : pi
      use Constants, only : Para_Jy2erg
      use Constants, only : Para_muJy2erg
      use Constants, only : Para_erg2Jy
      use Constants, only : Para_eV2erg
      use Constants, only : Para_keV2erg
      use Constants, only : Para_erg2eV
      use Constants, only : Para_erg2keV
      use Constants, only : Para_pc2cm
      use Constants, only : Para_kpc2cm
      use Constants, only : Para_Mpc2cm
      use Constants, only : Para_Gpc2cm
      use Constants, only : Para_Radian2Degree
      use Constants, only : Para_Degree2Radian
      use Constants, only : Para_Day2Second
      use Constants, only : Para_Year2Second
      use Constants, only : Para_h
      use Constants, only : Para_a
      use Constants, only : Para_c
      use Constants, only : Para_c_Inverse
      use Constants, only : Para_G
      use Constants, only : Para_m_Solor
      use Constants, only : Para_k
      use Constants, only : Para_k_keV
      use Constants, only : Para_Mu
      use Constants, only : Para_k_es
      use Constants, only : Para_m_e
      use Constants, only : Para_m_energy
      use Constants, only : Para_m_e_keV
      use Constants, only : Para_e
      use Constants, only : Para_m_p
      use Constants, only : Para_m_p_E
      use Constants, only : Para_m_p_DIV_m_e
      use Constants, only : Para_SigmaT
      use Constants, only : Para_rc
      use Constants, only : Para_Day
      use Constants, only : Para_Year
      use Constants, only : Para_Sigma
      use Constants, only : Para_Hz2eV
      use Constants, only : Para_Hz2keV
      use Constants, only : Para_Hz2MeV
      use Constants, only : Para_Hz2GeV
      use Constants, only : Para_TeV2Hz
      use Constants, only : Para_GeV2Hz
      use Constants, only : Para_MeV2Hz
      use Constants, only : Para_keV2Hz
      use Constants, only : Para_eV2Hz
      use Constants, only : Para_h_keV
      use Constants, only : Para_h_MeV
      use Constants, only : Para_h_GeV
      external f2pysetupfunc
      call f2pysetupfunc(zero,one,two,ten,pi,Para_Jy2erg,Para_muJy2erg,P&
     &ara_erg2Jy,Para_eV2erg,Para_keV2erg,Para_erg2eV,Para_erg2keV,Para_&
     &pc2cm,Para_kpc2cm,Para_Mpc2cm,Para_Gpc2cm,Para_Radian2Degree,Para_&
     &Degree2Radian,Para_Day2Second,Para_Year2Second,Para_h,Para_a,Para_&
     &c,Para_c_Inverse,Para_G,Para_m_Solor,Para_k,Para_k_keV,Para_Mu,Par&
     &a_k_es,Para_m_e,Para_m_energy,Para_m_e_keV,Para_e,Para_m_p,Para_m_&
     &p_E,Para_m_p_DIV_m_e,Para_SigmaT,Para_rc,Para_Day,Para_Year,Para_S&
     &igma,Para_Hz2eV,Para_Hz2keV,Para_Hz2MeV,Para_Hz2GeV,Para_TeV2Hz,Pa&
     &ra_GeV2Hz,Para_MeV2Hz,Para_keV2Hz,Para_eV2Hz,Para_h_keV,Para_h_MeV&
     &,Para_h_GeV)
      end subroutine f2pyinitConstants


